# Generated by Django 3.2.13 on 2022-06-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_alter_user_email'),
        ('todo_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=200, verbose_name='Информация')),
                ('test_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authnapp.user', verbose_name='пользователь'),
        ),
    ]
