# Generated by Django 3.2.13 on 2022-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_alter_user_email'),
        ('todo_web_app', '0002_auto_20220601_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project_title', models.CharField(max_length=128, verbose_name='тестовое название')),
                ('test_repo_link', models.URLField(max_length=256, verbose_name='тестовая ссылка на репозиторий')),
                ('test_users', models.ManyToManyField(to='authnapp.User', verbose_name='тестовые пользователи')),
            ],
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
