# Generated by Django 3.2.13 on 2022-06-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_alter_user_email'),
        ('todo_web_app', '0003_auto_20220608_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTestClass',
            new_name='TestProjectClass',
        ),
    ]
