# Generated by Django 3.2.13 on 2022-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('birthday_year', models.PositiveIntegerField(verbose_name='дата рождения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('city', models.CharField(default='Москва', max_length=128, verbose_name='город')),
                ('address', models.CharField(max_length=254, verbose_name='адресс')),
            ],
        ),
    ]
