# Generated by Django 3.2.13 on 2022-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Права доступа простого пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Права доступа администратора'),
        ),
    ]
